name: Testing hello-world-composite-action action
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say salam
    steps:
      - uses: actions/checkout@v4
      - id: salam
        uses: kcharymyrat/hello-world-composite-action@v3
        with:
          who-to-greet: "this is message running in my first action"
